/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestionproductosfinancieros.gui;

import com.mycompany.gestionproductosfinancieros.model.Chequera;
import com.mycompany.gestionproductosfinancieros.model.CuentaCorriente;
import com.mycompany.gestionproductosfinancieros.model.ProductoFinanciero;
import com.mycompany.gestionproductosfinancieros.servicios.ServicioProductoFinanciero;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Camilo
 */
public class GUIConsultarChequera extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIConsultarChequera.class.getName());
    private CuentaCorriente cuentaSeleccionada;
    private Chequera chequeraSeleccionada;
    private final ServicioProductoFinanciero servicioProductoFinanciero
            = ServicioProductoFinanciero.getInstancia();

    /**
     * Creates new form GUIConsultarChequera
     */
    public GUIConsultarChequera() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        cmbChequera = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtNumeroCheques = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNumeroCuenta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultar Chequera");

        jLabel6.setText("Estado:");

        cmbChequera.addActionListener(this::cmbChequeraActionPerformed);

        jLabel2.setText("Chequera:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        jLabel1.setText("N. cuenta: ");

        txtNumeroCuenta.addActionListener(this::txtNumeroCuentaActionPerformed);

        jLabel5.setText("N.cheques:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbChequera, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNumeroCuenta)
                    .addComponent(txtNumeroCheques, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbChequera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroCheques, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbChequeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbChequeraActionPerformed
        int posicion = cmbChequera.getSelectedIndex();

        if (posicion >= 0 && cuentaSeleccionada != null) {

            chequeraSeleccionada
                    = cuentaSeleccionada.getChequeras().get(posicion);

            txtNumeroCheques.setText(
                    String.valueOf(
                            chequeraSeleccionada.getNumeroCheques()
                    )
            );

            txtEstado.setText(
                    chequeraSeleccionada.getEstado()
            );
        }
    }//GEN-LAST:event_cmbChequeraActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            int numeroCuenta = Integer.parseInt(
                    txtNumeroCuenta.getText().trim()
            );

            Map<Integer, ProductoFinanciero> productos
                    = servicioProductoFinanciero.listarProductos();

            ProductoFinanciero pf = productos.get(numeroCuenta);

            if (!(pf instanceof CuentaCorriente)) {
                JOptionPane.showMessageDialog(
                        this,
                        "No se encontró una cuenta corriente con ese número."
                );
                return;
            }

            cuentaSeleccionada = (CuentaCorriente) pf;

            cmbChequera.removeAllItems();
            chequeraSeleccionada = null;

            for (Chequera chequera : cuentaSeleccionada.getChequeras()) {

                cmbChequera.addItem(
                        chequera.getNumeroCheques()
                        + " cheques - "
                        + chequera.getEstado()
                );
            }

            if (cmbChequera.getItemCount() == 0) {

                JOptionPane.showMessageDialog(
                        this,
                        "Esta cuenta no tiene chequeras."
                );

                txtNumeroCheques.setText("");
                txtEstado.setText("");

            } else {

                cmbChequera.setSelectedIndex(0);

                chequeraSeleccionada
                        = cuentaSeleccionada.getChequeras().get(0);

                txtNumeroCheques.setText(
                        String.valueOf(
                                chequeraSeleccionada.getNumeroCheques()
                        )
                );

                txtEstado.setText(
                        chequeraSeleccionada.getEstado()
                );
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Ingrese un número de cuenta válido."
            );
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtNumeroCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIConsultarChequera().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> cmbChequera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNumeroCheques;
    private javax.swing.JTextField txtNumeroCuenta;
    // End of variables declaration//GEN-END:variables
}
