/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestionproductosfinancieros.gui;

import com.mycompany.gestionproductosfinancieros.model.Chequera;
import com.mycompany.gestionproductosfinancieros.model.CuentaCorriente;
import com.mycompany.gestionproductosfinancieros.model.ProductoFinanciero;
import com.mycompany.gestionproductosfinancieros.servicios.ServicioProductoFinanciero;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Camilo
 */
public class GUIEliminarChequera extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIEliminarChequera.class.getName());
    private CuentaCorriente cuentaSeleccionada;
    private Chequera chequeraSeleccionada;
    private final ServicioProductoFinanciero servicioProductoFinanciero
            = ServicioProductoFinanciero.getInstancia();

    /**
     * Creates new form GUIEliminarChequera
     */
    public GUIEliminarChequera() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbChequera = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtNumeroCheques = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNumeroCuenta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eliminar Chequera");

        cmbChequera.addActionListener(this::cmbChequeraActionPerformed);

        jLabel2.setText("Chequera:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        jLabel1.setText("N. cuenta: ");

        txtNumeroCuenta.addActionListener(this::txtNumeroCuentaActionPerformed);

        jLabel5.setText("N.cheques:");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        jLabel6.setText("Estado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbChequera, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNumeroCuenta)
                    .addComponent(txtNumeroCheques, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstado))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEliminar)
                        .addGap(130, 130, 130))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbChequera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroCheques, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbChequeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbChequeraActionPerformed
        int posicion = cmbChequera.getSelectedIndex();

        if (posicion >= 0 && cuentaSeleccionada != null) {

            chequeraSeleccionada
                    = cuentaSeleccionada.getChequeras().get(posicion);

            txtNumeroCheques.setText(
                    String.valueOf(
                            chequeraSeleccionada.getNumeroCheques()
                    )
            );

            txtEstado.setText(
                    chequeraSeleccionada.getEstado()
            );
        }
    }//GEN-LAST:event_cmbChequeraActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            int numeroCuenta = Integer.parseInt(
                    txtNumeroCuenta.getText().trim()
            );

            Map<Integer, ProductoFinanciero> productos
                    = servicioProductoFinanciero.listarProductos();

            ProductoFinanciero pf = productos.get(numeroCuenta);

            if (!(pf instanceof CuentaCorriente)) {
                JOptionPane.showMessageDialog(
                        this,
                        "No se encontró una cuenta corriente con ese número."
                );
                return;
            }

            cuentaSeleccionada = (CuentaCorriente) pf;

            // Limpiar las opciones anteriores
            cmbChequera.removeAllItems();

            // Reiniciar la chequera seleccionada
            chequeraSeleccionada = null;

            // Cargar las chequeras de la cuenta
            for (Chequera chequera : cuentaSeleccionada.getChequeras()) {

                cmbChequera.addItem(
                        chequera.getNumeroCheques()
                        + " cheques - "
                        + chequera.getEstado()
                );
            }

            // Verificar si la cuenta tiene chequeras
            if (cmbChequera.getItemCount() == 0) {

                JOptionPane.showMessageDialog(
                        this,
                        "Esta cuenta no tiene chequeras."
                );

                txtNumeroCheques.setText("");
                txtEstado.setText("");

            } else {

                // Seleccionar automáticamente la primera chequera
                cmbChequera.setSelectedIndex(0);

                // Guardar la primera chequera seleccionada
                chequeraSeleccionada
                        = cuentaSeleccionada.getChequeras().get(0);

                // Mostrar sus datos
                txtNumeroCheques.setText(
                        String.valueOf(
                                chequeraSeleccionada.getNumeroCheques()
                        )
                );

                txtEstado.setText(
                        chequeraSeleccionada.getEstado()
                );
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Ingrese un número de cuenta válido."
            );
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtNumeroCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroCuentaActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (cuentaSeleccionada == null || chequeraSeleccionada == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Primero busque y seleccione una chequera."
            );
            return;
        }

        int respuesta = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de eliminar esta chequera?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION
        );

        if (respuesta == JOptionPane.YES_OPTION) {

            cuentaSeleccionada.eliminarChequera(chequeraSeleccionada);

            JOptionPane.showMessageDialog(
                    this,
                    "Chequera eliminada correctamente."
            );

            cmbChequera.removeAllItems();
            chequeraSeleccionada = null;
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIEliminarChequera().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cmbChequera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNumeroCheques;
    private javax.swing.JTextField txtNumeroCuenta;
    // End of variables declaration//GEN-END:variables
}
